# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='data',
            new_name='date',
        ),
    ]
