# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20180102_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price_per_ft2',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
