# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_price_per_ft2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price_per_ft2',
            field=models.FloatField(editable=False),
        ),
    ]
