# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20180104_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[(b'Terrace', b'Terrace House'), (b'Bunglow', b'Bunglow House'), (b'Apartment', b'Apartment House'), (b'Duplex', b'Duplex Apartment')], max_length=255),
        ),
    ]
