# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20180105_1822'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyType',
        ),
    ]
