# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20180105_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[(b'Terrace House', b'Terrace House'), (b'Bunglow House', b'Bunglow House'), (b'Apartment', b'Apartment'), (b'DuplexHouse', b'Duplex')], max_length=255),
        ),
    ]
